#set document(title: "Algebraic and Geometric Topology")
#set page(margin: 20pt)
#set text(size: 10pt)

#outline(title: none)
#pagebreak()

= §1: Point-Set Topology

== Metric Spaces and Topological Spaces

=== 1.1 Definition (Metric Space)

A *metric space* $(X, d)$ is a set $X$ together with a function $d: X times X -> RR_(gt.eq 0)$ satisfying:
- $d(x, y) = 0$ iff $x = y$
- $d(x, y) = d(y, x)$ (symmetry)
- $d(x, z) lt.eq d(x, y) + d(y, z)$ (triangle inequality)

=== 1.5 Definition (Topological Space)

A *topological space* $(X, cal(T))$ is a set $X$ with a collection $cal(T)$ of subsets (called *open sets*) satisfying:
- $emptyset, X in cal(T)$
- Arbitrary unions of open sets are open
- Finite intersections of open sets are open

A set $C subset X$ is *closed* if $X without C$ is open. The *interior* of $A$ is $A^circle.small = union\{U in cal(T) mid U subset A\}$, the *closure* is $overline(A) = inter\{C "closed" mid A subset C\}$, and the *boundary* is $partial A = overline(A) without A^circle.small$.

=== 1.11 Definition (Continuous Map)

A map $f: X -> Y$ between topological spaces is *continuous* if $f^(-1)(V)$ is open in $X$ for every open $V subset Y$.

A *homeomorphism* is a bijective continuous map with continuous inverse. If a homeomorphism $f: X -> Y$ exists, we write $X tilde.equiv Y$ and say $X$ and $Y$ are *homeomorphic*.

== Bases, Hausdorff, and Countability

=== 1.14 Definition (Basis)

A *basis* for a topology on $X$ is a collection $cal(B)$ of open sets such that every open set is a union of elements of $cal(B)$. The topology generated by $cal(B)$ is the collection of all unions of elements of $cal(B)$.

=== 1.20 Definition (Hausdorff Space)

A topological space $X$ is *Hausdorff* (or *$T_2$*) if for any $x != y$ in $X$, there exist disjoint open sets $U, V$ with $x in U$ and $y in V$.

Every metric space is Hausdorff. The cofinite topology on an infinite set is not Hausdorff.

=== 1.22 Definition (Second Countable)

$X$ is *second countable* if it has a countable basis. Metric spaces with a countable dense subset are second countable.

== Compactness

=== 1.25 Definition (Compact Space)

A topological space $X$ is *compact* if every open cover has a finite subcover: if $X = union_(i in I) U_i$ with each $U_i$ open, then $X = U_(i_1) union dots.c union U_(i_n)$ for some finite subcollection.

=== 1.30 Heine-Borel Theorem

_A subset of $RR^n$ is compact iff it is closed and bounded._

=== Key Properties

- Continuous images of compact spaces are compact.
- Compact subsets of Hausdorff spaces are closed.
- A continuous bijection from a compact space to a Hausdorff space is a homeomorphism.
- The product of two compact spaces is compact (Tychonoff).

== Paths and Connectedness

=== 1.38 Definition (Path)

A *path* in $X$ from $x_0$ to $x_1$ is a continuous map $gamma: [0,1] -> X$ with $gamma(0) = x_0$ and $gamma(1) = x_1$. $X$ is *path connected* if any two points are joined by a path.

=== 1.42 Definition (Connected Space)

$X$ is *connected* if it cannot be written as a disjoint union of two nonempty open sets. Path connectedness implies connectedness, but not conversely.

== Products, Disjoint Unions, and Key Examples

=== 1.49 Definition (Product Topology)

The *product* $X times Y$ has the topology generated by sets $U times V$ where $U$ is open in $X$ and $V$ is open in $Y$.

=== 1.54 Definition (Disjoint Union)

The *disjoint union* $X union.sq Y = (X times \{0\}) union (Y times \{1\})$ has the topology where $A$ is open iff $A inter X$ and $A inter Y$ are both open.

=== 1.60 Key Spaces

The *$n$-ball* is $B^n = \{x in RR^n mid ||x|| lt.eq 1\}$ with boundary $partial B^n = S^(n-1)$.

The *$n$-sphere* is $S^n = \{x in RR^(n+1) mid ||x|| = 1\}$. Note $S^0 = \{plus.minus 1\}$, $S^1$ is the circle, $S^2$ is the standard 2-sphere.

The *annulus* is $A = \{x in RR^2 mid 1 lt.eq ||x|| lt.eq 2\} tilde.equiv S^1 times [0,1]$.

The *torus* is $T^2 = S^1 times S^1$, homeomorphic to the square $[0,1]^2$ with opposite sides identified.

=== 1.68 Projective Space

The *real projective space* $RR P^n$ is the set of lines through the origin in $RR^(n+1)$, equivalently $S^n \/ (x tilde -x)$ (antipodal identification). As a topological space, $RR P^1 tilde.equiv S^1$ and $RR P^2$ is non-orientable.

= §2: Quotient Spaces

== Quotient Topology

=== 2.3 Definition (Quotient Space)

Let $X$ be a topological space and $tilde$ an equivalence relation on $X$. The *quotient space* $X \/ tilde$ is the set of equivalence classes $[x] = \{y in X mid y tilde x\}$, with the *quotient topology*: $U subset X\/tilde$ is open iff $q^(-1)(U)$ is open in $X$, where $q: X -> X\/tilde$ is the quotient map $q(x) = [x]$.

The quotient map $q$ is always continuous and surjective.

=== 2.5 Definition (Collapsing)

Given $A subset X$, the space $X \/ A$ is the quotient of $X$ by the equivalence relation that identifies all points of $A$. The equivalence classes are $A$ (as a single point) and $\{x\}$ for $x in X without A$.

=== 2.10 Definition (Wedge Sum)

The *wedge sum* $X ∨ Y$ of pointed spaces $(X, x_0)$ and $(Y, y_0)$ is $(X union.sq Y) \/ (x_0 tilde y_0)$, i.e., $X$ and $Y$ joined at a single point.

=== 2.14 Well-Defined Maps from Quotients

A map $f: X \/ tilde -> Y$ is well-defined iff $f(x) = f(x')$ whenever $x tilde x'$. In that case $f$ is continuous iff $f compose q$ is continuous.

=== 2.16 Proposition

_If $f: X -> Y$ is a continuous surjection, $X$ is compact, and $Y$ is Hausdorff, then $f$ is a quotient map. In particular, a continuous bijection from a compact space to a Hausdorff space is a homeomorphism._

=== 2.22 Examples

- $[0,1] \/ (0 tilde 1) tilde.equiv S^1$ (circle by identifying endpoints of interval).
- $S^n \/ (x tilde -x) tilde.equiv RR P^n$ (real projective space).
- The torus $T^2$ is the square $[0,1]^2$ with $(0,t) tilde (1,t)$ and $(s,0) tilde (s,1)$.
- The Klein bottle $K$ is $[0,1]^2$ with $(0,t) tilde (1,t)$ and $(s,0) tilde (1-s,1)$.
- The Möbius band is $[0,1] times [0,1]$ with $(0,t) tilde (1, 1-t)$.

= §3: Surfaces

== Basic Definitions

=== 3.1 Definition (Surface)

A *surface* is a compact, connected, Hausdorff, second-countable topological space $X$ such that every point has an open neighbourhood homeomorphic to $RR^2$ or to a half-plane $\{(x,y) mid y gt.eq 0\}$.

The *boundary* $partial X$ is the set of points with no neighbourhood homeomorphic to $RR^2$ (those with half-plane neighbourhoods). A surface *without boundary* has $partial X = emptyset$.

=== 3.10 Definition (Connected Sum)

The *connected sum* $X \# Y$ of two surfaces is formed by removing an open disk from each and gluing the resulting boundary circles together.

=== Standard Surfaces

The *sphere* $S^2$, the *torus* $T^2$, and the *real projective plane* $RR P^2$ are the basic examples.

The *$g$-holed torus* $Sigma_g$ is the connected sum of $g$ tori: $Sigma_g = T^2 \# T^2 \# dots.c \# T^2$ ($g$ times). $Sigma_0 = S^2$, $Sigma_1 = T^2$.

The *non-orientable surface* $N_k$ is the connected sum of $k$ projective planes: $N_k = RR P^2 \# dots.c \# RR P^2$ ($k$ times). $N_1 = RR P^2$, $N_2 = K$ (Klein bottle).

== Polygon Representations

=== 3.22 Definition (Polygon Word)

A surface can be described by a *polygon* with edges identified in pairs, specified by a *word*: label each edge with a letter, using $a$ for one direction and $a^(-1)$ for the reverse. Reading clockwise gives the word.

- Sphere: $a a^(-1)$ (digon) or $a b a^(-1) b^(-1)$ (square with both pairs of opposite sides identified, but wait — that's the torus)
- Torus $T^2$: $a b a^(-1) b^(-1)$
- Projective plane $RR P^2$: $a a$ (digon with both edges identified in the same direction)
- Klein bottle $K$: $a b a^(-1) b$ or $a a b b$
- $Sigma_g$: $a_1 b_1 a_1^(-1) b_1^(-1) a_2 b_2 a_2^(-1) b_2^(-1) dots.c a_g b_g a_g^(-1) b_g^(-1)$
- $N_k$: $a_1 a_1 a_2 a_2 dots.c a_k a_k$

== Classification of Compact Surfaces

=== 3.39 Classification Theorem

_Every compact connected surface without boundary is homeomorphic to exactly one of:_
- _The sphere $S^2 = Sigma_0$_
- _An orientable surface $Sigma_g$ for $g gt.eq 1$ (connected sum of $g$ tori)_
- _A non-orientable surface $N_k$ for $k gt.eq 1$ (connected sum of $k$ projective planes)_

These are all distinct (non-homeomorphic).

=== Orientability

A surface is *orientable* if it has no Möbius band embedded in it. The surfaces $Sigma_g$ are orientable; the surfaces $N_k$ are not. Orientability is a topological invariant.

== Triangulation and Cutting/Pasting

=== 3.44 Definition (Triangulation)

A *triangulation* of a surface $X$ is a homeomorphism from $X$ to a simplicial complex (a topological space built by gluing triangles). Every compact surface has a triangulation.

The *Euler characteristic* $chi(X) = V - E + F$ (vertices minus edges plus faces) is a topological invariant: $chi(Sigma_g) = 2 - 2g$ and $chi(N_k) = 2 - k$.

=== 3.48 Cutting and Pasting

The proof of the Classification Theorem proceeds by taking a triangulated surface, cutting along paths, and reassembling into a standard polygon form (using Euler characteristic and careful edge identifications).

=== 3.54 Dyck's Theorem

_If $X$ is a compact non-orientable surface and $X = Sigma_g \# N_k$ conceptually, then $T^2 \# RR P^2 tilde.equiv RR P^2 \# RR P^2 \# RR P^2 = N_3$._

More precisely: $Sigma_g \# N_k tilde.equiv N_(2g + k)$ for any $g gt.eq 0$, $k gt.eq 1$.

=== 3.67 Manifolds

A *topological $n$-manifold* is a Hausdorff second-countable space where every point has a neighbourhood homeomorphic to $RR^n$. Surfaces are compact 2-manifolds (possibly with boundary).

= §4: The Fundamental Group

== Paths, Loops, and Homotopy

=== 4.3 Definition (Concatenation)

For paths $gamma, delta: [0,1] -> X$ with $gamma(1) = delta(0)$, the *concatenation* $gamma * delta$ is the path
$ (gamma * delta)(t) = cases(gamma(2t) & "if" t in [0, 1\/2], delta(2t - 1) & "if" t in [1\/2, 1]) $

A *loop based at $x_0$* is a path $gamma$ with $gamma(0) = gamma(1) = x_0$.

=== 4.6 Definition (Homotopy of Paths)

A *homotopy* from $gamma_0$ to $gamma_1$ (both paths from $x_0$ to $x_1$) is a continuous map $H: [0,1] times [0,1] -> X$ with $H(s, 0) = gamma_0(s)$, $H(s, 1) = gamma_1(s)$, $H(0, t) = x_0$, $H(1, t) = x_1$ for all $s, t$.

Two paths are *homotopic rel endpoints*, written $gamma_0 tilde.eq gamma_1$, if such a homotopy exists. This is an equivalence relation.

=== 4.13 Definition (Fundamental Group)

The *fundamental group* $pi_1(X, x_0)$ is the set of homotopy classes $[gamma]$ of loops based at $x_0$, with multiplication $[gamma][delta] = [gamma * delta]$.

The identity is the class of the constant loop $e(t) = x_0$. The inverse of $[gamma]$ is $[overline(gamma)]$ where $overline(gamma)(t) = gamma(1 - t)$ is the reverse path.

=== 4.16 Theorem (Well-definedness and Group Axioms)

_$pi_1(X, x_0)$ is a group: multiplication is well-defined, associative up to homotopy, with identity and inverses._

*Associativity* $[alpha * (beta * gamma)] = [(alpha * beta) * gamma]$: the two concatenations differ by a reparametrisation, which gives a homotopy.

*Inverses:* the concatenation $gamma * overline(gamma)$ is homotopic to the constant loop (shrink to the basepoint).

=== 4.20 Basepoint Independence

If $X$ is path connected, $pi_1(X, x_0) tilde.equiv pi_1(X, x_1)$ for any $x_0, x_1 in X$. The isomorphism is given by conjugation by a path from $x_0$ to $x_1$: $[gamma] arrow.r.bar [sigma^(-1) * gamma * sigma]$. For path-connected spaces we often write $pi_1(X)$.

=== 4.22 Examples

- $pi_1(RR^n) = \{e\}$ (contractible, all loops null-homotopic).
- $pi_1(S^1) tilde.equiv ZZ$ (covered in §5 via winding numbers).
- $pi_1(S^n) = \{e\}$ for $n gt.eq 2$ (simply connected).
- $pi_1(T^2) tilde.equiv ZZ^2$ (abelian, generators are the two standard loops).

= §5: Winding Numbers and Covering Spaces

== The Punctured Plane and Winding Numbers

=== 5.3 Setup

Consider the *punctured plane* $X = RR^2 without \{0\}$. Loops in $X$ based at $1 in RR^2$ are characterised by how many times they wind around the origin.

=== 5.11 Definition (Winding Number)

Given a loop $gamma: [0,1] -> RR^2 without \{0\}$ based at $1$, write $gamma(t) = r(t) e^(i theta(t))$ where $r(t) > 0$ and $theta(t)$ is a continuous choice of angle with $theta(0) = 0$. The *winding number* is $n(gamma) = theta(1) / (2 pi) in ZZ$.

This is a homotopy invariant and gives an isomorphism $pi_1(RR^2 without \{0\}, 1) tilde.equiv ZZ$, hence $pi_1(S^1) tilde.equiv ZZ$.

== Covering Spaces

=== 5.3 Definition (Covering Map)

A continuous surjection $p: tilde(X) -> X$ is a *covering map* if every $x in X$ has an open neighbourhood $U$ such that $p^(-1)(U) = union.sq_alpha V_alpha$ (disjoint union of open sets), with each $p|_(V_alpha): V_alpha -> U$ a homeomorphism. The space $tilde(X)$ is a *covering space* of $X$.

=== Examples

- $p: RR -> S^1$, $p(t) = e^(2 pi i t)$: $RR$ covers $S^1$, sheets are the intervals $[n, n+1]$.
- $p: S^n -> RR P^n$, $p(x) = [x]$ (antipodal map): $S^n$ is a 2-sheeted cover of $RR P^n$.

=== 5.10 Path Lifting Theorem

_Let $p: tilde(X) -> X$ be a covering map, $gamma: [0,1] -> X$ a path with $gamma(0) = x_0$, and $tilde(x)_0 in p^(-1)(x_0)$. Then there exists a unique path $tilde(gamma): [0,1] -> tilde(X)$ with $tilde(gamma)(0) = tilde(x)_0$ and $p compose tilde(gamma) = gamma$._

=== 5.16 Homotopy Lifting Theorem

_Let $p: tilde(X) -> X$ be a covering map, $H: [0,1] times [0,1] -> X$ a homotopy of paths, and $tilde(gamma)_0$ a lift of $H(dot, 0)$. Then there is a unique homotopy $tilde(H): [0,1] times [0,1] -> tilde(X)$ lifting $H$ with $tilde(H)(s, 0) = tilde(gamma)_0(s)$._

*Corollary.* Homotopic paths in $X$ lift to homotopic paths in $tilde(X)$ (with the same starting point). This is used to show the induced map $p_*: pi_1(tilde(X)) -> pi_1(X)$ is injective.

=== 5.28, 5.29 Versions for $S^1$

Applying the lifting theorems to $p: RR -> S^1$: every loop in $S^1$ lifts to a path in $RR$, and the endpoint of the lifted path gives the winding number. Homotopic loops have the same winding number.

== Simply Connected Spaces

=== 5.30 Definition (Simply Connected)

A path-connected space $X$ is *simply connected* if $pi_1(X) = \{e\}$, i.e., every loop is null-homotopic.

=== 5.34 Definition (Universal Cover)

A covering map $p: tilde(X) -> X$ is a *universal cover* if $tilde(X)$ is simply connected. Universal covers are unique up to isomorphism (as covering spaces).

=== 5.38 Example: Universal Cover of $S^1$

$p: RR -> S^1$, $t arrow.r.bar e^(2 pi i t)$, is the universal cover. $pi_1(S^1) tilde.equiv ZZ tilde.equiv "Deck"(tilde(X) \/ X)$ (deck transformations = covering transformations).

=== 5.40 Fundamental Group via Covering Theory

_Let $p: tilde(X) -> X$ be a universal cover. The *deck transformation group* is $"Deck"(tilde(X) \/ X) = \{phi: tilde(X) -> tilde(X) mid p compose phi = p\}$, and $pi_1(X, x_0) tilde.equiv "Deck"(tilde(X) \/ X)$._

=== 5.42 Example: $pi_1(RR P^n) tilde.equiv ZZ_2$

$S^n -> RR P^n$ is the universal cover for $n gt.eq 2$ (since $S^n$ is simply connected). The only non-trivial deck transformation is the antipodal map $x arrow.r.bar -x$, so $"Deck" tilde.equiv ZZ_2$.

= §6: More on Fundamental Groups

== Classical Applications

=== 6.1 Brouwer Fixed Point Theorem

_Every continuous map $f: B^2 -> B^2$ has a fixed point._

*Proof.* Suppose $f$ has no fixed point. Define $r: B^2 -> S^1$ by $r(x) = $ the intersection of the ray from $f(x)$ through $x$ with $S^1$. Then $r$ is a continuous retraction: $r|_(S^1) = "id"$. But the inclusion $i: S^1 -> B^2$ induces $i_*: pi_1(S^1) -> pi_1(B^2)$, i.e., $ZZ -> \{e\}$, and $r_*: pi_1(B^2) -> pi_1(S^1)$, i.e., $\{e\} -> ZZ$. Then $r_* compose i_* = (r compose i)_* = "id"_*$ would force the identity $ZZ -> ZZ$ to factor through $\{e\}$, contradiction.

=== 6.2 No Retraction Theorem

_There is no retraction $r: B^n -> S^(n-1)$ (i.e., no continuous $r$ with $r|_(S^(n-1)) = "id"$). Hence every continuous $f: B^n -> B^n$ has a fixed point._

=== 6.3 Fundamental Theorem of Algebra

_Every non-constant complex polynomial $p(z)$ has a root._

*Proof.* Suppose $p(z) = z^n + a_(n-1) z^(n-1) + dots.c + a_0$ has no root. For large $R$, $p$ restricted to $|z| = R$ has winding number $n$ around the origin. As $R -> 0$, the winding number would have to drop to $0$, but winding number is a homotopy invariant and $p$ is never $0$, giving a contradiction.

== Products and Induced Homomorphisms

=== 6.8 Theorem (Products)

$pi_1(X times Y, (x_0, y_0)) tilde.equiv pi_1(X, x_0) times pi_1(Y, y_0).$

*Proof.* A loop $gamma: [0,1] -> X times Y$ is the same as a pair $(gamma_1, gamma_2)$ of loops in $X$ and $Y$. The isomorphism is $[gamma] arrow.r.bar ([gamma_1], [gamma_2])$.

*Example.* $pi_1(T^2) = pi_1(S^1 times S^1) tilde.equiv ZZ times ZZ = ZZ^2$.

=== 6.12 Definition (Induced Homomorphism)

A continuous map $f: (X, x_0) -> (Y, y_0)$ (preserving basepoints) induces a group homomorphism $f_*: pi_1(X, x_0) -> pi_1(Y, y_0)$ by $f_*([gamma]) = [f compose gamma]$.

=== 6.19 Theorem (Functoriality)

- $(g compose f)_* = g_* compose f_*$
- $"id"_* = "id"$

Hence if $f: X -> Y$ is a homeomorphism, $f_*: pi_1(X) -> pi_1(Y)$ is an isomorphism. The fundamental group is a topological invariant.

== Homotopy Invariance

=== 6.21 Free Homotopy

A *free homotopy* between loops $gamma_0$ and $gamma_1$ (not necessarily based) is a continuous $H: [0,1] times [0,1] -> X$ with $H(s,0) = gamma_0(s)$ and $H(s,1) = gamma_1(s)$ (no basepoint condition).

Freely homotopic loops represent conjugate elements in $\pi_1$: if $H(0, t) = sigma(t)$ is the path traced by the basepoint, then $[gamma_1] = [sigma]^(-1) [gamma_0] [sigma]$.

=== 6.52 Definition (Deformation Retraction)

A *deformation retraction* of $X$ onto $A subset X$ is a continuous $H: X times [0,1] -> X$ with $H(x, 0) = x$, $H(x, 1) in A$, and $H(a, t) = a$ for all $a in A$, $t in [0,1]$.

If $A$ is a deformation retract of $X$, then $i: A -> X$ induces an isomorphism $pi_1(A) tilde.equiv pi_1(X)$.

=== 6.58 Definition (Homotopy Equivalence)

Maps $f: X -> Y$ and $g: Y -> X$ are a *homotopy equivalence* if $g compose f tilde.eq "id"_X$ and $f compose g tilde.eq "id"_Y$. We write $X tilde.eq Y$ and say they are *homotopy equivalent*.

Homotopy equivalent spaces have isomorphic fundamental groups. Homeomorphic spaces are homotopy equivalent, but not vice versa.

*Example.* $RR^2 without \{0\}$ deformation retracts onto $S^1$, so $pi_1(RR^2 without \{0\}) tilde.equiv ZZ$.

= §7: Van Kampen's Theorem

== Group Presentations and Free Groups

=== 7.1 Definition (Group Presentation)

A *presentation* $chevron.l A mid R chevron.r$ describes a group with generators $A$ and relations $R$. The group is $F(A) \/ N(R)$ where $F(A)$ is the free group on $A$ and $N(R)$ is the normal closure of $R$.

=== 7.12 Definition (Free Group)

The *free group* $F(A)$ on a set $A$ is the group of reduced words in $A union A^(-1)$ with concatenation and reduction. It has the universal property: any function $A -> G$ extends uniquely to a homomorphism $F(A) -> G$.

=== 7.19 Definition (Free Product)

The *free product* $G * H$ of groups $G = chevron.l A mid R chevron.r$ and $H = chevron.l B mid S chevron.r$ (with $A, B$ disjoint) is
$ G * H = chevron.l A union B mid R union S chevron.r. $
Elements are reduced words alternating between elements of $G$ and $H$.

*Example.* $ZZ * ZZ = chevron.l a, b mid chevron.r = F(\{a, b\})$ (free group on two generators).

== Van Kampen's Theorem

=== 7.32 Van Kampen's Theorem (Basic Version)

_Let $X = U union V$ where $U, V$ are open, path connected, and $U inter V$ is path connected and simply connected ($pi_1(U inter V) = \{e\}$). Then_
$ pi_1(X) tilde.equiv pi_1(U) * pi_1(V). $

*Proof sketch.* Every loop in $X$ can be subdivided into loops lying in $U$ or $V$ (by compactness). Any relation must come from a loop in $U inter V$, but $U inter V$ is simply connected so imposes no relations beyond those already in $\pi_1(U)$ and $\pi_1(V)$.

=== Application: Wedge Sums

For $X = X_1 ∨ X_2$ (wedge sum of path-connected spaces, basepoint at the wedge point), applying Van Kampen with $U$ and $V$ small open sets around each summand:
$ pi_1(X_1 ∨ X_2) tilde.equiv pi_1(X_1) * pi_1(X_2). $

*Example.* $pi_1(S^1 ∨ S^1) tilde.equiv ZZ * ZZ = F_2$ (free group on 2 generators).

=== 7.45 Van Kampen's Theorem (Full Version)

_Let $X = U union V$ where $U, V$ are open and path connected, $U inter V$ is path connected (but not necessarily simply connected). Let $i_U: pi_1(U inter V) -> pi_1(U)$ and $i_V: pi_1(U inter V) -> pi_1(V)$ be the maps induced by inclusion. Then_
$ pi_1(X) tilde.equiv pi_1(U) *_(pi_1(U inter V)) pi_1(V) $
_the *amalgamated free product* (or *pushout*): the free product $pi_1(U) * pi_1(V)$ modulo the normal closure of $\{i_U(g) i_V(g)^(-1) mid g in pi_1(U inter V)\}$._

*Explicitly:* if $\pi_1(U) = chevron.l A mid R chevron.r$, $\pi_1(V) = chevron.l B mid S chevron.r$, and $\pi_1(U inter V)$ has generators $c_k$ with $i_U(c_k) = w_k(A)$ and $i_V(c_k) = v_k(B)$, then
$ pi_1(X) = chevron.l A, B mid R, S, w_k(A) = v_k(B) "for all" k chevron.r. $

=== Application: Fundamental Groups of Surfaces

For the torus $T^2$ with polygon word $a b a^(-1) b^(-1)$: let $U$ = interior of polygon (contractible, $\pi_1 = \{e\}$) and $V$ = neighbourhood of boundary. The boundary loop gives one relation:
$ pi_1(T^2) = chevron.l a, b mid a b a^(-1) b^(-1) chevron.r tilde.equiv ZZ^2. $

For $Sigma_g$: $pi_1(Sigma_g) = chevron.l a_1, b_1, dots, a_g, b_g mid [a_1, b_1][a_2, b_2] dots.c [a_g, b_g] chevron.r$ (one relation).

For $N_k = RR P^2 \# dots.c \# RR P^2$ ($k$ times): $pi_1(N_k) = chevron.l a_1, dots, a_k mid a_1^2 a_2^2 dots.c a_k^2 chevron.r$.

In particular:
- $pi_1(RR P^2) = chevron.l a mid a^2 chevron.r tilde.equiv ZZ_2$
- $pi_1(K) = chevron.l a, b mid a b a^(-1) b chevron.r$ (Klein bottle group)

== Abelianisations and Classification

=== 7.51 Definition (Abelianisation)

The *abelianisation* of a group $G$ is $G^"ab" = G \/ [G, G]$, the largest abelian quotient. If $G = chevron.l A mid R chevron.r$, then $G^"ab" = chevron.l A mid R, [a_i, a_j] "for all" a_i, a_j chevron.r$.

The *first homology group* $H_1(X) := pi_1(X)^"ab"$.

=== 7.56 Theorem (Classification via Abelianisation)

The abelianisations distinguish the surfaces:
- $H_1(Sigma_g) = pi_1(Sigma_g)^"ab" tilde.equiv ZZ^(2g)$ (free abelian of rank $2g$)
- $H_1(N_k) = pi_1(N_k)^"ab" tilde.equiv ZZ^(k-1) plus.o ZZ_2$ (free part of rank $k-1$, plus $ZZ_2$ torsion)
- $H_1(S^2) = 0$

Since $H_1$ is a topological invariant, these surfaces are all topologically distinct, completing the proof of the Classification Theorem 3.39 via algebraic methods.

=== 7.3.2 Summary: Proof of Classification of Compact Surfaces

Combining geometric (cutting/pasting, triangulation) and algebraic (fundamental groups, abelianisation) methods:

1. *Existence*: every compact surface can be reduced (by cutting/pasting) to one of the standard polygon words $Sigma_g$ or $N_k$.
2. *Distinctness*: the Euler characteristic $chi$ distinguishes $Sigma_g$ from $Sigma_{g'}$ (and $N_k$ from $N_{k'}$), while orientability distinguishes the $Sigma_g$ family from the $N_k$ family. Alternatively, $H_1$ distinguishes all of them simultaneously: $H_1(Sigma_g) tilde.equiv ZZ^(2g)$ (torsion-free) while $H_1(N_k) tilde.equiv ZZ^(k-1) plus.o ZZ_2$ (has $ZZ_2$ torsion).
