name: CI

on:
  pull_request:
    paths:
    - '**/*.typ'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: typst-community/setup-typst@v4

    - name: Build Typst Files
      run: make compile

    - name: Rename PDFs with folder names
      run: make rename

    - name: List PDFs
      run: tree


    - name: Upload PDFs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdf-notes
        path: ./notes/**/**/*_notes.pdf
        retention-days: 5

